# Generated by Django 3.2.5 on 2021-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_auto_20210719_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
