# Generated by Django 3.2.5 on 2021-07-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_order_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderedProduct',
        ),
    ]
